(defun my-common-mode-auto-pair ()
  (interactive)
  (make-local-variable 'skeleton-pair-alist)
  (setq skeleton-pair-alist '(
(? ? _ "''")
(? ? _ """")
(? ? _ "()")
(? ? _ "[]")
(?{ \n > _ \n ?} >)))
  (setq skeleton-pair t)
  (local-set-key (kbd "(") 'skeleton-pair-insert-maybe)
  (local-set-key (kbd "\"") 'skeleton-pair-insert-maybe)
  (local-set-key (kbd "{") 'skeleton-pair-insert-maybe)
  (local-set-key (kbd "\'") 'skeleton-pair-insert-maybe)
  (local-set-key (kbd "[") 'skeleton-pair-insert-maybe))
(add-hook 'c-mode-hook 'my-common-mode-auto-pair)
(add-hook 'c++-mode-hook 'my-common-mode-auto-pair)
(add-hook 'java-mode-hook 'my-common-mode-auto-pair)
(add-hook 'lisp-mode-hook 'my-common-mode-auto-pair)
(add-hook 'php-mode-hook 'my-common-mode-auto-pair)
(add-hook 'python-mode-hook 'my-common-mode-auto-pair)
(add-hook 'scheme-mode-hook 'my-common-mode-auto-pair)
(add-hook 'sql-mode-hook 'my-common-mode-auto-pair)
(add-hook 'emacs-lisp-mode-hook 'my-common-mode-auto-pair)
(add-hook 'slime-repl-mode-hook 'my-common-mode-auto-pair)
;;specified for js-mode. i don't want {} auto-pair,it's annoying badly
(defun my-common-mode-auto-pair2 ()
  (interactive)
  (make-local-variable 'skeleton-pair-alist)
  (setq skeleton-pair-alist '(
(? ? _ "''")
(? ? _ """")
(? ? _ "()")
(? ? _ "[]")))
  (setq skeleton-pair t)
  (local-set-key (kbd "(") 'skeleton-pair-insert-maybe)
  (local-set-key (kbd "\"") 'skeleton-pair-insert-maybe)
  (local-set-key (kbd "\'") 'skeleton-pair-insert-maybe)
  (local-set-key (kbd "[") 'skeleton-pair-insert-maybe))

(add-hook 'js-mode-hook 'my-common-mode-auto-pair2)
(add-hook 'css-mode-hook 'my-common-mode-auto-pair2)
(add-hook 'shell-mode-hook 'my-common-mode-auto-pair2)
(add-hook 'html-mode-hook 'my-common-mode-auto-pair2)
(add-hook 'web-mode-hook 'my-common-mode-auto-pair2)
(add-hook 'py-shell-hook 'my-common-mode-auto-pair2)
(add-hook 'inferior-js-mode-hook 'my-common-mode-auto-pair2)
(add-hook 'js2-mode-hook 'my-common-mode-auto-pair2)
(add-hook 'org-mode-hook 'my-common-mode-auto-pair2)
(add-hook 'ruby-mode-hook 'my-common-mode-auto-pair2)
;; some modes will use text-mode-hook as default.for example latex-mode, if 
;; you use latex-mode-hook to replace below statement, as a result, we can't 
;; get the corresponding close part automatically.
(add-hook 'text-mode-hook 'my-common-mode-auto-pair2)
